/**
 * ImageNet classes that represent fish and marine species
 * These are the classes MobileNet can recognize from its pre-training
 */
export const FISH_CATEGORIES = [
  'goldfish',
  'great white shark',
  'tiger shark',
  'hammerhead',
  'electric ray',
  'stingray',
  'cock',
  'hen',
  'ostrich',
  'brambling',
  'goldfinch',
  'house finch',
  'junco',
  'indigo bunting',
  'robin',
  'bulbul',
  'jay',
  'magpie',
  'chickadee',
  'water ouzel',
  'kite',
  'bald eagle',
  'vulture',
  'great grey owl',
  'jellyfish',
  'sea anemone',
  'brain coral',
  'flatworm',
  'nematode',
  'conch',
  'snail',
  'slug',
  'sea slug',
  'chiton',
  'chambered nautilus',
  'Dungeness crab',
  'rock crab',
  'fiddler crab',
  'king crab',
  'American lobster',
  'spiny lobster',
  'crayfish',
  'hermit crab',
  'isopod',
  'white stork',
  'black stork',
  'spoonbill',
  'flamingo',
  'little blue heron',
  'American egret',
  'bittern',
  'crane',
  'limpkin',
  'European gallinule',
  'American coot',
  'bustard',
  'ruddy turnstone',
  'red-backed sandpiper',
  'redshank',
  'dowitcher',
  'oystercatcher',
  'pelican',
  'king penguin',
  'albatross',
  'grey whale',
  'killer whale',
  'dugong',
  'sea lion',
  'Chihuahua',
  'Japanese spaniel',
  'Maltese dog',
  'Pekinese',
  'Shih-Tzu',
  'Blenheim spaniel',
  'papillon',
  'toy terrier',
  'Rhodesian ridgeback',
  'Afghan hound',
  'basset',
  'beagle',
  'bloodhound',
  'bluetick',
  'black-and-tan coonhound',
  'Walker hound',
  'English foxhound',
  'redbone',
  'borzoi',
  'Irish wolfhound',
  'Italian greyhound',
  'whippet',
  'Ibizan hound',
  'Norwegian elkhound',
  'otterhound',
  'Saluki',
  'Scottish deerhound',
  'Weimaraner',
  'Staffordshire bullterrier',
  'American Staffordshire terrier',
  'Bedlington terrier',
  'Border terrier',
  'Kerry blue terrier',
  'Irish terrier',
  'Norfolk terrier',
  'Norwich terrier',
  'Yorkshire terrier',
  'wire-haired fox terrier',
  'Lakeland terrier',
  'Sealyham terrier',
  'Airedale',
  'cairn',
  'Australian terrier',
  'Dandie Dinmont',
  'Boston bull',
  'miniature schnauzer',
  'giant schnauzer',
  'standard schnauzer',
  'Scotch terrier',
  'Tibetan terrier',
  'silky terrier',
  'soft-coated wheaten terrier',
  'West Highland white terrier',
  'Lhasa',
  'flat-coated retriever',
  'curly-coated retriever',
  'golden retriever',
  'Labrador retriever',
  'Chesapeake Bay retriever',
  'German short-haired pointer',
  'vizsla',
  'English setter',
  'Irish setter',
  'Gordon setter',
  'Brittany spaniel',
  'clumber',
  'English springer',
  'Welsh springer spaniel',
  'cocker spaniel',
  'Sussex spaniel',
  'Irish water spaniel',
  'kuvasz',
  'schipperke',
  'groenendael',
  'malinois',
  'briard',
  'kelpie',
  'komondor',
  'Old English sheepdog',
  'Shetland sheepdog',
  'collie',
  'Border collie',
  'Bouvier des Flandres',
  'Rottweiler',
  'German shepherd',
  'Doberman',
  'miniature pinscher',
  'Greater Swiss Mountain dog',
  'Bernese mountain dog',
  'Appenzeller',
  'EntleBucher',
  'boxer',
  'bull mastiff',
  'Tibetan mastiff',
  'French bulldog',
  'Great Dane',
  'Saint Bernard',
  'Eskimo dog',
  'malamute',
  'Siberian husky',
  'affenpinscher',
  'basenji',
  'pug',
  'Leonberg',
  'Newfoundland',
  'Great Pyrenees',
  'Samoyed',
  'Pomeranian',
  'chow',
  'keeshond',
  'Brabancon griffon',
  'Pembroke',
  'Cardigan',
  'toy poodle',
  'miniature poodle',
  'standard poodle',
  'Mexican hairless',
  'dingo',
  'dhole',
  'African hunting dog',
  'tench',
  'barracouta',
  'coho',
  'rock beauty',
  'anemone fish',
  'sturgeon',
  'gar',
  'lionfish',
  'puffer',
  'abacus',
  'abaya',
  'academic gown',
  'accordion',
  'acoustic guitar',
  'aircraft carrier',
  'airliner',
];

/**
 * Check if a MobileNet prediction is a fish or marine species
 * @param {string} className - The class name from MobileNet
 * @returns {boolean}
 */
export function isFishCategory(className) {
  const lowerClass = className.toLowerCase();
  
  // Direct match
  if (FISH_CATEGORIES.some(cat => lowerClass.includes(cat.toLowerCase()))) {
    return true;
  }
  
  // Additional keywords for marine life
  const marineKeywords = [
    'fish', 'shark', 'ray', 'whale', 'dolphin', 'seal', 'sea lion',
    'jellyfish', 'coral', 'crab', 'lobster', 'octopus', 'squid',
    'starfish', 'sea', 'marine', 'aquatic', 'turtle', 'penguin'
  ];
  
  return marineKeywords.some(keyword => lowerClass.includes(keyword));
}
